### ISSUE TITLE
parrottmux


### ISSUE THREAD

**Issue by nu3nio** [sabamdarif/parrot-gui#2]

**Comment by Praveennishad007** [comment]
Hello sir Parrot  not installing  in my termux but using this command ubuntu is starting  download then sir how can I solve this problem.

**Comment by Praveennishad007** [comment]
Please give this answer

**Comment by sabamdarif** [comment]
Wait I rewrite the code again

**Comment by sabamdarif** [comment]
> Please give this answer

Wait I rewrite the code again

**Comment by Praveennishad007** [comment]
Thanks sir by the Way where are you from and your instagram id

**Comment by sabamdarif** [comment]
Try now it fixed

**Comment by sabamdarif** [comment]
Oo
